"""empty message

Revision ID: d970cb672211
Revises: 
Create Date: 2023-06-21 17:38:30.712854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd970cb672211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('age', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie_name', sa.String(length=100), nullable=False),
    sa.Column('perfil_categorias_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_categorias_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_name', sa.String(length=100), nullable=False),
    sa.Column('practice_time', sa.String(length=20), nullable=False),
    sa.Column('about_you', sa.String(length=100), nullable=False),
    sa.Column('categories_talent', sa.String(length=100), nullable=False),
    sa.Column('range_talent', sa.String(length=100), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('imagetalent_url', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.Boolean(), nullable=True),
    sa.Column('perfil_solicitante_id', sa.Integer(), nullable=False),
    sa.Column('perfil_receptor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_receptor_id'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['perfil_solicitante_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talent_request')
    op.drop_table('talent')
    op.drop_table('categories')
    op.drop_table('perfil')
    op.drop_table('user')
    # ### end Alembic commands ###
